# Generates Util/NativeNames.inc (hash -> "NAMESPACE::NAME") from Natives/natives.h.
# Rerun whenever natives.h changes. Usage (from repo root):
#   pwsh -File Solution/source/Util/GenNativeNames.ps1
param(
    [string]$InputPath = (Join-Path $PSScriptRoot '..' 'Natives' 'natives.h' | Resolve-Path),
    [string]$OutputPath = (Join-Path $PSScriptRoot 'NativeNames.inc')
)

$lines = Get-Content -Path $InputPath
$namespace = ''
$pendingName = ''
$expectName = $false
$expectHash = $false
$entries = New-Object System.Collections.Generic.List[object]
$skipped = 0

foreach ($line in $lines) {
    if ($line -match '^\s*namespace\s+([A-Za-z0-9_]+)') {
        $namespace = $Matches[1]
        $pendingName = ''
        $expectName = $false
        $expectHash = $false
        continue
    }
    if ($line -match '^\s*\}\s*//\s*namespace') {
        $namespace = ''
        $pendingName = ''
        $expectName = $false
        $expectHash = $false
        continue
    }
    if ($expectHash -and $line -match '^\s*0x([0-9A-Fa-f]+)') {
        $hash = $Matches[1]
        $expectHash = $false
    } elseif ($line -match 'invoke<[^>]+>\(\s*0x([0-9A-Fa-f]+)') {
        $hash = $Matches[1]
    } elseif ($line -match 'invoke<[^>]+>\(\s*$') {
        $expectHash = $true
        continue
    } else {
        $hash = $null
    }
    if ($hash) {
        if ($namespace -ne '' -and $pendingName -ne '') {
            $entries.Add([pscustomobject]@{ Hash = [uint64]('0x' + $hash); Name = "$namespace::$pendingName" })
        } else {
            $skipped++
        }
        $pendingName = ''
        continue
    }
    if ($line -match '^\s*static\s+(?:[\w:<>*&]+\s+)+?([A-Za-z_]\w*)\s*\(') {
        $pendingName = $Matches[1]
        $expectName = $false
        continue
    }
    if ($line -match '^\s*static\s+[\w:<>*&]+\s*$') {
        $expectName = $true
        continue
    }
    if ($expectName -and $line -match '^\s*([A-Za-z_]\w*)\s*\(') {
        $pendingName = $Matches[1]
        $expectName = $false
        continue
    }
}

$seen = @{}
$unique = New-Object System.Collections.Generic.List[object]
foreach ($e in ($entries | Sort-Object { $_.Hash })) {
    if ($seen.ContainsKey($e.Hash)) {
        Write-Warning ("duplicate hash 0x{0:X16} ({1}, already mapped to {2})" -f $e.Hash, $e.Name, $seen[$e.Hash])
        continue
    }
    $seen[$e.Hash] = $e.Name
    $unique.Add($e)
}

$out = New-Object System.Collections.Generic.List[string]
$out.Add('// Auto-generated by GenNativeNames.ps1 from Natives/natives.h. Do not edit.')
$out.Add('#pragma once')
$out.Add('#include <cstddef>')
$out.Add('namespace ige { namespace NativeNames {')
$out.Add('struct Entry { unsigned long long hash; const char* name; };')
$out.Add('constexpr Entry kEntries[] = {')
foreach ($e in $unique) {
    $out.Add(('    {{0x{0:X16}ULL, "{1}"}},' -f $e.Hash, $e.Name))
}
$out.Add('};')
$out.Add('constexpr std::size_t kEntryCount = sizeof(kEntries) / sizeof(kEntries[0]);')
$out.Add('} } // namespace NativeNames, ige')
[System.IO.File]::WriteAllLines($OutputPath, $out)

"{0} entries ({1} unique), {2} skipped without name" -f $entries.Count, $unique.Count, $skipped
